// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OOP_ASU_5.Infrastructure.Data;

namespace OOP_ASU_5.Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OOP_ASU_5.Domain.ContentLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContentLinks");
                });

            modelBuilder.Entity("OOP_ASU_5.Domain.Discipline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DisciplineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("OOP_ASU_5.Domain.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContentLinkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DifficultyCoefficient")
                        .HasColumnType("float");

                    b.Property<string>("ExerciseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ExercisesBlockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContentLinkId");

                    b.HasIndex("ExercisesBlockId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("OOP_ASU_5.Domain.ExerciseVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContentLinkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DifficultyCoefficient")
                        .HasColumnType("float");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContentLinkId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("LessonId");

                    b.ToTable("ExerciseVariants");
                });

            modelBuilder.Entity("OOP_ASU_5.Domain.ExercisesBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContentLinkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DifficultyCoefficient")
                        .HasColumnType("float");

                    b.Property<string>("ExerciseBlockType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContentLinkId");

                    b.ToTable("ExercisesBlocks");
                });

            modelBuilder.Entity("OOP_ASU_5.Domain.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContentLinkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExerciseBlockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExercisesBlockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Laboriousness")
                        .HasColumnType("int");

                    b.Property<string>("LessonType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContentLinkId");

                    b.HasIndex("ExercisesBlockId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("OOP_ASU_5.Domain.Option", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("FreeFormat")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("OOP_ASU_5.Domain.Discipline", b =>
                {
                    b.HasOne("OOP_ASU_5.Domain.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("OOP_ASU_5.Domain.Exercise", b =>
                {
                    b.HasOne("OOP_ASU_5.Domain.ContentLink", "ContentLink")
                        .WithMany()
                        .HasForeignKey("ContentLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OOP_ASU_5.Domain.ExercisesBlock", "ExercisesBlock")
                        .WithMany("Exercises")
                        .HasForeignKey("ExercisesBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentLink");

                    b.Navigation("ExercisesBlock");
                });

            modelBuilder.Entity("OOP_ASU_5.Domain.ExerciseVariant", b =>
                {
                    b.HasOne("OOP_ASU_5.Domain.ContentLink", "ContentLink")
                        .WithMany()
                        .HasForeignKey("ContentLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OOP_ASU_5.Domain.Exercise", "Exercise")
                        .WithMany("ExercisesVariants")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OOP_ASU_5.Domain.Lesson", null)
                        .WithMany("ExerciseVariants")
                        .HasForeignKey("LessonId");

                    b.Navigation("ContentLink");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("OOP_ASU_5.Domain.ExercisesBlock", b =>
                {
                    b.HasOne("OOP_ASU_5.Domain.ContentLink", "ContentLink")
                        .WithMany()
                        .HasForeignKey("ContentLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentLink");
                });

            modelBuilder.Entity("OOP_ASU_5.Domain.Lesson", b =>
                {
                    b.HasOne("OOP_ASU_5.Domain.ContentLink", "ContentLink")
                        .WithMany()
                        .HasForeignKey("ContentLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OOP_ASU_5.Domain.ExercisesBlock", "ExercisesBlock")
                        .WithMany()
                        .HasForeignKey("ExercisesBlockId");

                    b.Navigation("ContentLink");

                    b.Navigation("ExercisesBlock");
                });

            modelBuilder.Entity("OOP_ASU_5.Domain.Option", b =>
                {
                    b.HasOne("OOP_ASU_5.Domain.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("OOP_ASU_5.Domain.Exercise", b =>
                {
                    b.Navigation("ExercisesVariants");
                });

            modelBuilder.Entity("OOP_ASU_5.Domain.ExercisesBlock", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("OOP_ASU_5.Domain.Lesson", b =>
                {
                    b.Navigation("ExerciseVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
